predictor_cols:
  - 'TX_DATE'
  - 'TX_AMOUNT'
  - 'TX_DURING_WEEKEND'
  - 'TX_DURING_NIGHT'
  - 'CUSTOMER_ID_NB_TX_1DAY_WINDOW'
  - 'CUSTOMER_ID_NB_TX_7DAY_WINDOW'
  - 'CUSTOMER_ID_NB_TX_30DAY_WINDOW'
  - 'CUSTOMER_ID_AVG_AMOUNT_1DAY_WINDOW'
  - 'CUSTOMER_ID_AVG_AMOUNT_7DAY_WINDOW'
  - 'CUSTOMER_ID_AVG_AMOUNT_30DAY_WINDOW'
  - 'TERMINAL_ID_NB_TX_1DAY_WINDOW'
  - 'TERMINAL_ID_NB_TX_7DAY_WINDOW'
  - 'TERMINAL_ID_NB_TX_30DAY_WINDOW'
  - 'TERMINAL_ID_RISK_1DAY_WINDOW' 
  - 'TERMINAL_ID_RISK_7DAY_WINDOW'
  - 'TERMINAL_ID_RISK_30DAY_WINDOW'
  - 'TX_FRAUD'

contamination_value: 0.009